export const taskList = [
  {id: 1, task: 'Fazer comida', done: false},
  {id: 2, task: 'Fazer compras', done: true},
  {id: 3, task: 'Fazer caminhada', done: true},
  {id: 4, task: 'Ir passear com os cachorros', done: false},
  {id: 1, task: 'Fazer comida', done: false},
  {id: 2, task: 'Fazer compras', done: true},
  {id: 3, task: 'Fazer caminhada', done: true},
  {id: 4, task: 'Ir passear com os cachorros', done: false},
  {id: 1, task: 'Fazer comida', done: false},
  {id: 2, task: 'Fazer compras', done: true},
  {id: 3, task: 'Fazer caminhada', done: true},
  {id: 4, task: 'Ir passear com os cachorros', done: false},
  {id: 1, task: 'Fazer comida', done: false},
  {id: 2, task: 'Fazer compras', done: true},
  {id: 3, task: 'Fazer caminhada', done: true},
  {id: 4, task: 'Ir passear com os cachorros', done: false},
  {id: 1, task: 'Fazer comida', done: false},
  {id: 2, task: 'Fazer compras', done: true},
  {id: 3, task: 'Fazer caminhada', done: true},
  {id: 4, task: 'Ir passear com os cachorros', done: false},
  {id: 1, task: 'Fazer comida', done: false},
  {id: 2, task: 'Fazer compras', done: true},
  {id: 3, task: 'Fazer caminhada', done: true},
  {id: 4, task: 'Ir passear com os cachorros', done: false},
  {id: 1, task: 'Fazer comida', done: false},
  {id: 2, task: 'Fazer compras', done: true},
  {id: 3, task: 'Fazer caminhada', done: true},
  {id: 4, task: 'Ir passear com os cachorros', done: false},
  {id: 1, task: 'Fazer comida', done: false},
  {id: 2, task: 'Fazer compras', done: true},
  {id: 3, task: 'Fazer caminhada', done: true},
  {id: 4, task: 'Ir passear com os cachorros', done: false},
  {id: 1, task: 'Fazer comida', done: false},
  {id: 2, task: 'Fazer compras', done: true},
  {id: 3, task: 'Fazer caminhada', done: true},
  {id: 4, task: 'Ir passear com os cachorros', done: false},
  {id: 1, task: 'Fazer comida', done: false},
  {id: 2, task: 'Fazer compras', done: true},
  {id: 3, task: 'Fazer caminhada', done: true},
  {id: 4, task: 'Ir passear com os cachorros', done: false},
  {id: 1, task: 'Fazer comida', done: false},
  {id: 2, task: 'Fazer compras', done: true},
  {id: 3, task: 'Fazer caminhada', done: true},
  {id: 4, task: 'Ir passear com os cachorros', done: false},
  {id: 1, task: 'Fazer comida', done: false},
  {id: 2, task: 'Fazer compras', done: true},
  {id: 3, task: 'Fazer caminhada', done: true},
  {id: 4, task: 'Ir passear com os cachorros', done: false},
];
